// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.12.4
// source: bds.proto

package BranchDeliverySystem

import (
	context "context"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type Empty struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Empty) Reset() {
	*x = Empty{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bds_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_bds_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_bds_proto_rawDescGZIP(), []int{0}
}

type User struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ID_USER  int64  `protobuf:"varint,1,opt,name=ID_USER,json=IDUSER,proto3" json:"ID_USER,omitempty"`
	NAMA     string `protobuf:"bytes,2,opt,name=NAMA,proto3" json:"NAMA,omitempty"`
	PASSWORD string `protobuf:"bytes,3,opt,name=PASSWORD,proto3" json:"PASSWORD,omitempty"`
	ROLE     string `protobuf:"bytes,4,opt,name=ROLE,proto3" json:"ROLE,omitempty"`
	CABANG   string `protobuf:"bytes,5,opt,name=CABANG,proto3" json:"CABANG,omitempty"`
}

func (x *User) Reset() {
	*x = User{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bds_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *User) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*User) ProtoMessage() {}

func (x *User) ProtoReflect() protoreflect.Message {
	mi := &file_bds_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use User.ProtoReflect.Descriptor instead.
func (*User) Descriptor() ([]byte, []int) {
	return file_bds_proto_rawDescGZIP(), []int{1}
}

func (x *User) GetID_USER() int64 {
	if x != nil {
		return x.ID_USER
	}
	return 0
}

func (x *User) GetNAMA() string {
	if x != nil {
		return x.NAMA
	}
	return ""
}

func (x *User) GetPASSWORD() string {
	if x != nil {
		return x.PASSWORD
	}
	return ""
}

func (x *User) GetROLE() string {
	if x != nil {
		return x.ROLE
	}
	return ""
}

func (x *User) GetCABANG() string {
	if x != nil {
		return x.CABANG
	}
	return ""
}

type SETORTUNAI struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	NOREK   int64  `protobuf:"varint,1,opt,name=NOREK,proto3" json:"NOREK,omitempty"`
	NOMINAL int64  `protobuf:"varint,2,opt,name=NOMINAL,proto3" json:"NOMINAL,omitempty"`
	BERITA  string `protobuf:"bytes,3,opt,name=BERITA,proto3" json:"BERITA,omitempty"`
}

func (x *SETORTUNAI) Reset() {
	*x = SETORTUNAI{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bds_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SETORTUNAI) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SETORTUNAI) ProtoMessage() {}

func (x *SETORTUNAI) ProtoReflect() protoreflect.Message {
	mi := &file_bds_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SETORTUNAI.ProtoReflect.Descriptor instead.
func (*SETORTUNAI) Descriptor() ([]byte, []int) {
	return file_bds_proto_rawDescGZIP(), []int{2}
}

func (x *SETORTUNAI) GetNOREK() int64 {
	if x != nil {
		return x.NOREK
	}
	return 0
}

func (x *SETORTUNAI) GetNOMINAL() int64 {
	if x != nil {
		return x.NOMINAL
	}
	return 0
}

func (x *SETORTUNAI) GetBERITA() string {
	if x != nil {
		return x.BERITA
	}
	return ""
}

type NASABAH struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CIF           int64  `protobuf:"varint,1,opt,name=CIF,proto3" json:"CIF,omitempty"`
	NIK           int64  `protobuf:"varint,2,opt,name=NIK,proto3" json:"NIK,omitempty"`
	NAMA          string `protobuf:"bytes,3,opt,name=NAMA,proto3" json:"NAMA,omitempty"`
	TEMPAT_LAHIR  string `protobuf:"bytes,4,opt,name=TEMPAT_LAHIR,json=TEMPATLAHIR,proto3" json:"TEMPAT_LAHIR,omitempty"`
	TANGGAL_LAHIR string `protobuf:"bytes,5,opt,name=TANGGAL_LAHIR,json=TANGGALLAHIR,proto3" json:"TANGGAL_LAHIR,omitempty"`
	ALAMAT        string `protobuf:"bytes,6,opt,name=ALAMAT,proto3" json:"ALAMAT,omitempty"`
	NO_TELP       string `protobuf:"bytes,7,opt,name=NO_TELP,json=NOTELP,proto3" json:"NO_TELP,omitempty"`
}

func (x *NASABAH) Reset() {
	*x = NASABAH{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bds_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NASABAH) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NASABAH) ProtoMessage() {}

func (x *NASABAH) ProtoReflect() protoreflect.Message {
	mi := &file_bds_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NASABAH.ProtoReflect.Descriptor instead.
func (*NASABAH) Descriptor() ([]byte, []int) {
	return file_bds_proto_rawDescGZIP(), []int{3}
}

func (x *NASABAH) GetCIF() int64 {
	if x != nil {
		return x.CIF
	}
	return 0
}

func (x *NASABAH) GetNIK() int64 {
	if x != nil {
		return x.NIK
	}
	return 0
}

func (x *NASABAH) GetNAMA() string {
	if x != nil {
		return x.NAMA
	}
	return ""
}

func (x *NASABAH) GetTEMPAT_LAHIR() string {
	if x != nil {
		return x.TEMPAT_LAHIR
	}
	return ""
}

func (x *NASABAH) GetTANGGAL_LAHIR() string {
	if x != nil {
		return x.TANGGAL_LAHIR
	}
	return ""
}

func (x *NASABAH) GetALAMAT() string {
	if x != nil {
		return x.ALAMAT
	}
	return ""
}

func (x *NASABAH) GetNO_TELP() string {
	if x != nil {
		return x.NO_TELP
	}
	return ""
}

type NASABAH_DETAIL struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CIF         int64 `protobuf:"varint,1,opt,name=CIF,proto3" json:"CIF,omitempty"`
	NO_REKENING int64 `protobuf:"varint,2,opt,name=NO_REKENING,json=NOREKENING,proto3" json:"NO_REKENING,omitempty"`
	SALDO       int64 `protobuf:"varint,3,opt,name=SALDO,proto3" json:"SALDO,omitempty"`
}

func (x *NASABAH_DETAIL) Reset() {
	*x = NASABAH_DETAIL{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bds_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NASABAH_DETAIL) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NASABAH_DETAIL) ProtoMessage() {}

func (x *NASABAH_DETAIL) ProtoReflect() protoreflect.Message {
	mi := &file_bds_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NASABAH_DETAIL.ProtoReflect.Descriptor instead.
func (*NASABAH_DETAIL) Descriptor() ([]byte, []int) {
	return file_bds_proto_rawDescGZIP(), []int{4}
}

func (x *NASABAH_DETAIL) GetCIF() int64 {
	if x != nil {
		return x.CIF
	}
	return 0
}

func (x *NASABAH_DETAIL) GetNO_REKENING() int64 {
	if x != nil {
		return x.NO_REKENING
	}
	return 0
}

func (x *NASABAH_DETAIL) GetSALDO() int64 {
	if x != nil {
		return x.SALDO
	}
	return 0
}

type TRANSAKSI struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ID              int64  `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	ID_USER         int64  `protobuf:"varint,2,opt,name=ID_USER,json=IDUSER,proto3" json:"ID_USER,omitempty"`
	NO_REKENING     int64  `protobuf:"varint,3,opt,name=NO_REKENING,json=NOREKENING,proto3" json:"NO_REKENING,omitempty"`
	TANGGAL         string `protobuf:"bytes,4,opt,name=TANGGAL,proto3" json:"TANGGAL,omitempty"`
	JENIS_TRANSAKSI string `protobuf:"bytes,5,opt,name=JENIS_TRANSAKSI,json=JENISTRANSAKSI,proto3" json:"JENIS_TRANSAKSI,omitempty"`
	NOMINAL         string `protobuf:"bytes,6,opt,name=NOMINAL,proto3" json:"NOMINAL,omitempty"`
	SALDO           int64  `protobuf:"varint,7,opt,name=SALDO,proto3" json:"SALDO,omitempty"`
	BERITA          string `protobuf:"bytes,8,opt,name=BERITA,proto3" json:"BERITA,omitempty"`
}

func (x *TRANSAKSI) Reset() {
	*x = TRANSAKSI{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bds_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TRANSAKSI) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TRANSAKSI) ProtoMessage() {}

func (x *TRANSAKSI) ProtoReflect() protoreflect.Message {
	mi := &file_bds_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TRANSAKSI.ProtoReflect.Descriptor instead.
func (*TRANSAKSI) Descriptor() ([]byte, []int) {
	return file_bds_proto_rawDescGZIP(), []int{5}
}

func (x *TRANSAKSI) GetID() int64 {
	if x != nil {
		return x.ID
	}
	return 0
}

func (x *TRANSAKSI) GetID_USER() int64 {
	if x != nil {
		return x.ID_USER
	}
	return 0
}

func (x *TRANSAKSI) GetNO_REKENING() int64 {
	if x != nil {
		return x.NO_REKENING
	}
	return 0
}

func (x *TRANSAKSI) GetTANGGAL() string {
	if x != nil {
		return x.TANGGAL
	}
	return ""
}

func (x *TRANSAKSI) GetJENIS_TRANSAKSI() string {
	if x != nil {
		return x.JENIS_TRANSAKSI
	}
	return ""
}

func (x *TRANSAKSI) GetNOMINAL() string {
	if x != nil {
		return x.NOMINAL
	}
	return ""
}

func (x *TRANSAKSI) GetSALDO() int64 {
	if x != nil {
		return x.SALDO
	}
	return 0
}

func (x *TRANSAKSI) GetBERITA() string {
	if x != nil {
		return x.BERITA
	}
	return ""
}

var File_bds_proto protoreflect.FileDescriptor

var file_bds_proto_rawDesc = []byte{
	0x0a, 0x09, 0x62, 0x64, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x14, 0x42, 0x72, 0x61,
	0x6e, 0x63, 0x68, 0x44, 0x65, 0x6c, 0x69, 0x76, 0x65, 0x72, 0x79, 0x53, 0x79, 0x73, 0x74, 0x65,
	0x6d, 0x22, 0x07, 0x0a, 0x05, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x22, 0x7b, 0x0a, 0x04, 0x55, 0x73,
	0x65, 0x72, 0x12, 0x17, 0x0a, 0x07, 0x49, 0x44, 0x5f, 0x55, 0x53, 0x45, 0x52, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x06, 0x49, 0x44, 0x55, 0x53, 0x45, 0x52, 0x12, 0x12, 0x0a, 0x04, 0x4e,
	0x41, 0x4d, 0x41, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x4e, 0x41, 0x4d, 0x41, 0x12,
	0x1a, 0x0a, 0x08, 0x50, 0x41, 0x53, 0x53, 0x57, 0x4f, 0x52, 0x44, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x08, 0x50, 0x41, 0x53, 0x53, 0x57, 0x4f, 0x52, 0x44, 0x12, 0x12, 0x0a, 0x04, 0x52,
	0x4f, 0x4c, 0x45, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x52, 0x4f, 0x4c, 0x45, 0x12,
	0x16, 0x0a, 0x06, 0x43, 0x41, 0x42, 0x41, 0x4e, 0x47, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x06, 0x43, 0x41, 0x42, 0x41, 0x4e, 0x47, 0x22, 0x54, 0x0a, 0x0a, 0x53, 0x45, 0x54, 0x4f, 0x52,
	0x54, 0x55, 0x4e, 0x41, 0x49, 0x12, 0x14, 0x0a, 0x05, 0x4e, 0x4f, 0x52, 0x45, 0x4b, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x4e, 0x4f, 0x52, 0x45, 0x4b, 0x12, 0x18, 0x0a, 0x07, 0x4e,
	0x4f, 0x4d, 0x49, 0x4e, 0x41, 0x4c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x4e, 0x4f,
	0x4d, 0x49, 0x4e, 0x41, 0x4c, 0x12, 0x16, 0x0a, 0x06, 0x42, 0x45, 0x52, 0x49, 0x54, 0x41, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x42, 0x45, 0x52, 0x49, 0x54, 0x41, 0x22, 0xba, 0x01,
	0x0a, 0x07, 0x4e, 0x41, 0x53, 0x41, 0x42, 0x41, 0x48, 0x12, 0x10, 0x0a, 0x03, 0x43, 0x49, 0x46,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x03, 0x43, 0x49, 0x46, 0x12, 0x10, 0x0a, 0x03, 0x4e,
	0x49, 0x4b, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x03, 0x4e, 0x49, 0x4b, 0x12, 0x12, 0x0a,
	0x04, 0x4e, 0x41, 0x4d, 0x41, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x4e, 0x41, 0x4d,
	0x41, 0x12, 0x21, 0x0a, 0x0c, 0x54, 0x45, 0x4d, 0x50, 0x41, 0x54, 0x5f, 0x4c, 0x41, 0x48, 0x49,
	0x52, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x54, 0x45, 0x4d, 0x50, 0x41, 0x54, 0x4c,
	0x41, 0x48, 0x49, 0x52, 0x12, 0x23, 0x0a, 0x0d, 0x54, 0x41, 0x4e, 0x47, 0x47, 0x41, 0x4c, 0x5f,
	0x4c, 0x41, 0x48, 0x49, 0x52, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x54, 0x41, 0x4e,
	0x47, 0x47, 0x41, 0x4c, 0x4c, 0x41, 0x48, 0x49, 0x52, 0x12, 0x16, 0x0a, 0x06, 0x41, 0x4c, 0x41,
	0x4d, 0x41, 0x54, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x41, 0x4c, 0x41, 0x4d, 0x41,
	0x54, 0x12, 0x17, 0x0a, 0x07, 0x4e, 0x4f, 0x5f, 0x54, 0x45, 0x4c, 0x50, 0x18, 0x07, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x06, 0x4e, 0x4f, 0x54, 0x45, 0x4c, 0x50, 0x22, 0x59, 0x0a, 0x0e, 0x4e, 0x41,
	0x53, 0x41, 0x42, 0x41, 0x48, 0x5f, 0x44, 0x45, 0x54, 0x41, 0x49, 0x4c, 0x12, 0x10, 0x0a, 0x03,
	0x43, 0x49, 0x46, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x03, 0x43, 0x49, 0x46, 0x12, 0x1f,
	0x0a, 0x0b, 0x4e, 0x4f, 0x5f, 0x52, 0x45, 0x4b, 0x45, 0x4e, 0x49, 0x4e, 0x47, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x0a, 0x4e, 0x4f, 0x52, 0x45, 0x4b, 0x45, 0x4e, 0x49, 0x4e, 0x47, 0x12,
	0x14, 0x0a, 0x05, 0x53, 0x41, 0x4c, 0x44, 0x4f, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05,
	0x53, 0x41, 0x4c, 0x44, 0x4f, 0x22, 0xe0, 0x01, 0x0a, 0x09, 0x54, 0x52, 0x41, 0x4e, 0x53, 0x41,
	0x4b, 0x53, 0x49, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x02, 0x49, 0x44, 0x12, 0x17, 0x0a, 0x07, 0x49, 0x44, 0x5f, 0x55, 0x53, 0x45, 0x52, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x49, 0x44, 0x55, 0x53, 0x45, 0x52, 0x12, 0x1f, 0x0a, 0x0b,
	0x4e, 0x4f, 0x5f, 0x52, 0x45, 0x4b, 0x45, 0x4e, 0x49, 0x4e, 0x47, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x0a, 0x4e, 0x4f, 0x52, 0x45, 0x4b, 0x45, 0x4e, 0x49, 0x4e, 0x47, 0x12, 0x18, 0x0a,
	0x07, 0x54, 0x41, 0x4e, 0x47, 0x47, 0x41, 0x4c, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07,
	0x54, 0x41, 0x4e, 0x47, 0x47, 0x41, 0x4c, 0x12, 0x27, 0x0a, 0x0f, 0x4a, 0x45, 0x4e, 0x49, 0x53,
	0x5f, 0x54, 0x52, 0x41, 0x4e, 0x53, 0x41, 0x4b, 0x53, 0x49, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0e, 0x4a, 0x45, 0x4e, 0x49, 0x53, 0x54, 0x52, 0x41, 0x4e, 0x53, 0x41, 0x4b, 0x53, 0x49,
	0x12, 0x18, 0x0a, 0x07, 0x4e, 0x4f, 0x4d, 0x49, 0x4e, 0x41, 0x4c, 0x18, 0x06, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x07, 0x4e, 0x4f, 0x4d, 0x49, 0x4e, 0x41, 0x4c, 0x12, 0x14, 0x0a, 0x05, 0x53, 0x41,
	0x4c, 0x44, 0x4f, 0x18, 0x07, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x53, 0x41, 0x4c, 0x44, 0x4f,
	0x12, 0x16, 0x0a, 0x06, 0x42, 0x45, 0x52, 0x49, 0x54, 0x41, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x06, 0x42, 0x45, 0x52, 0x49, 0x54, 0x41, 0x32, 0x9c, 0x01, 0x0a, 0x03, 0x41, 0x64, 0x64,
	0x12, 0x43, 0x0a, 0x09, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x55, 0x73, 0x65, 0x72, 0x12, 0x1a, 0x2e,
	0x42, 0x72, 0x61, 0x6e, 0x63, 0x68, 0x44, 0x65, 0x6c, 0x69, 0x76, 0x65, 0x72, 0x79, 0x53, 0x79,
	0x73, 0x74, 0x65, 0x6d, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x1a, 0x1a, 0x2e, 0x42, 0x72, 0x61, 0x6e,
	0x63, 0x68, 0x44, 0x65, 0x6c, 0x69, 0x76, 0x65, 0x72, 0x79, 0x53, 0x79, 0x73, 0x74, 0x65, 0x6d,
	0x2e, 0x55, 0x73, 0x65, 0x72, 0x12, 0x50, 0x0a, 0x0a, 0x53, 0x65, 0x74, 0x6f, 0x72, 0x54, 0x75,
	0x6e, 0x61, 0x69, 0x12, 0x20, 0x2e, 0x42, 0x72, 0x61, 0x6e, 0x63, 0x68, 0x44, 0x65, 0x6c, 0x69,
	0x76, 0x65, 0x72, 0x79, 0x53, 0x79, 0x73, 0x74, 0x65, 0x6d, 0x2e, 0x53, 0x45, 0x54, 0x4f, 0x52,
	0x54, 0x55, 0x4e, 0x41, 0x49, 0x1a, 0x20, 0x2e, 0x42, 0x72, 0x61, 0x6e, 0x63, 0x68, 0x44, 0x65,
	0x6c, 0x69, 0x76, 0x65, 0x72, 0x79, 0x53, 0x79, 0x73, 0x74, 0x65, 0x6d, 0x2e, 0x53, 0x45, 0x54,
	0x4f, 0x52, 0x54, 0x55, 0x4e, 0x41, 0x49, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_bds_proto_rawDescOnce sync.Once
	file_bds_proto_rawDescData = file_bds_proto_rawDesc
)

func file_bds_proto_rawDescGZIP() []byte {
	file_bds_proto_rawDescOnce.Do(func() {
		file_bds_proto_rawDescData = protoimpl.X.CompressGZIP(file_bds_proto_rawDescData)
	})
	return file_bds_proto_rawDescData
}

var file_bds_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_bds_proto_goTypes = []interface{}{
	(*Empty)(nil),          // 0: BranchDeliverySystem.Empty
	(*User)(nil),           // 1: BranchDeliverySystem.User
	(*SETORTUNAI)(nil),     // 2: BranchDeliverySystem.SETORTUNAI
	(*NASABAH)(nil),        // 3: BranchDeliverySystem.NASABAH
	(*NASABAH_DETAIL)(nil), // 4: BranchDeliverySystem.NASABAH_DETAIL
	(*TRANSAKSI)(nil),      // 5: BranchDeliverySystem.TRANSAKSI
}
var file_bds_proto_depIdxs = []int32{
	1, // 0: BranchDeliverySystem.Add.LoginUser:input_type -> BranchDeliverySystem.User
	2, // 1: BranchDeliverySystem.Add.SetorTunai:input_type -> BranchDeliverySystem.SETORTUNAI
	1, // 2: BranchDeliverySystem.Add.LoginUser:output_type -> BranchDeliverySystem.User
	2, // 3: BranchDeliverySystem.Add.SetorTunai:output_type -> BranchDeliverySystem.SETORTUNAI
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_bds_proto_init() }
func file_bds_proto_init() {
	if File_bds_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_bds_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Empty); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bds_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*User); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bds_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SETORTUNAI); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bds_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NASABAH); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bds_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NASABAH_DETAIL); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bds_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TRANSAKSI); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_bds_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_bds_proto_goTypes,
		DependencyIndexes: file_bds_proto_depIdxs,
		MessageInfos:      file_bds_proto_msgTypes,
	}.Build()
	File_bds_proto = out.File
	file_bds_proto_rawDesc = nil
	file_bds_proto_goTypes = nil
	file_bds_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// AddClient is the client API for Add service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type AddClient interface {
	LoginUser(ctx context.Context, in *User, opts ...grpc.CallOption) (*User, error)
	SetorTunai(ctx context.Context, in *SETORTUNAI, opts ...grpc.CallOption) (*SETORTUNAI, error)
}

type addClient struct {
	cc grpc.ClientConnInterface
}

func NewAddClient(cc grpc.ClientConnInterface) AddClient {
	return &addClient{cc}
}

func (c *addClient) LoginUser(ctx context.Context, in *User, opts ...grpc.CallOption) (*User, error) {
	out := new(User)
	err := c.cc.Invoke(ctx, "/BranchDeliverySystem.Add/LoginUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *addClient) SetorTunai(ctx context.Context, in *SETORTUNAI, opts ...grpc.CallOption) (*SETORTUNAI, error) {
	out := new(SETORTUNAI)
	err := c.cc.Invoke(ctx, "/BranchDeliverySystem.Add/SetorTunai", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AddServer is the server API for Add service.
type AddServer interface {
	LoginUser(context.Context, *User) (*User, error)
	SetorTunai(context.Context, *SETORTUNAI) (*SETORTUNAI, error)
}

// UnimplementedAddServer can be embedded to have forward compatible implementations.
type UnimplementedAddServer struct {
}

func (*UnimplementedAddServer) LoginUser(context.Context, *User) (*User, error) {
	return nil, status.Errorf(codes.Unimplemented, "method LoginUser not implemented")
}
func (*UnimplementedAddServer) SetorTunai(context.Context, *SETORTUNAI) (*SETORTUNAI, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetorTunai not implemented")
}

func RegisterAddServer(s *grpc.Server, srv AddServer) {
	s.RegisterService(&_Add_serviceDesc, srv)
}

func _Add_LoginUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(User)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AddServer).LoginUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/BranchDeliverySystem.Add/LoginUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AddServer).LoginUser(ctx, req.(*User))
	}
	return interceptor(ctx, in, info, handler)
}

func _Add_SetorTunai_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SETORTUNAI)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AddServer).SetorTunai(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/BranchDeliverySystem.Add/SetorTunai",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AddServer).SetorTunai(ctx, req.(*SETORTUNAI))
	}
	return interceptor(ctx, in, info, handler)
}

var _Add_serviceDesc = grpc.ServiceDesc{
	ServiceName: "BranchDeliverySystem.Add",
	HandlerType: (*AddServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "LoginUser",
			Handler:    _Add_LoginUser_Handler,
		},
		{
			MethodName: "SetorTunai",
			Handler:    _Add_SetorTunai_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "bds.proto",
}
